<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '#INVALID' => '',
    'Active' => 'Đang hoạt động',
    'Add New' => 'Thêm mới',
    'Are you sure you want to delete this item?' => '',
    'Assign' => '',
    'Assign Role' => 'Gán vai trò',
    'Assign roles to ' => '',
    'Auth Key' => '',
    'Avatar' => 'Ảnh đại diện',
    'Back' => 'Quay lại',
    'Birthday' => 'Ngày sinh',
    'Block' => 'Chặn',
    'Blocked' => 'Bị Chặn',
    'Change Password' => 'Đổi mật khẩu',
    'Comfirm Passwords don\'t match' => '',
    'Confirm Password' => 'Xác nhận mật khẩu',
    'Contacts' => 'Danh bạ',
    'Create' => 'Tạo',
    'Create Employee' => '',
    'Created At' => 'Tạo lúc',
    'Created By' => 'Tạo bởi',
    'Data provided by' => 'Dữ liệu cung cấp bởi',
    'Delete' => 'Xóa',
    'Deleted' => 'Đã Xóa',
    'Development Document' => 'Tài liệu phát triển',
    'Document is not available for this language' => 'Tài liệu không có sẵn cho ngôn ngữ này',
    'Documents' => 'Tài liệu',
    'Email' => '',
    'Employees' => 'Nhân viên',
    'Famale' => 'Nữ',
    'First' => 'Đầu',
    'Fullname' => 'Họ và tên',
    'Gender' => 'Giới tính',
    'Home' => 'Trang chủ',
    'ID' => '',
    'Incorrect password.' => '',
    'Incorrect username.' => '',
    'Information' => 'Thông tin',
    'Last' => 'Cuối',
    'Log out' => 'Đăng xuất',
    'Male' => 'Nam',
    'Manage' => '',
    'Meanwhile, you may return to Home' => 'Trong khi đó, bạn có thể trở về Trang chủ',
    'Monthly' => 'Tháng',
    'New Paswsord' => 'Mật khẩu mới',
    'Not found employee with specify id' => '',
    'Not yet assign any role for this employee' => 'Chưa chỉ định bất kỳ vai trò nào cho nhân viên này',
    'Not yet set role' => 'Không thiết lập vai trò',
    'Old Paswsord' => 'Mật khẩu cũ',
    'Old password is incorrect' => '',
    'Password' => 'Mật khẩu',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Phone' => 'Điện thoại',
    'Please contact us if you think this is a server error. Thank you.' => 'Hãy liên hệ với chúng tôi nếu bạn nghĩ rằng đây là một lỗi máy chủ. Cảm ơn.',
    'Profile' => 'Tiểu sử',
    'Profile of' => '',
    'Role' => 'Vai trò',
    'Roles' => 'Các vai trò',
    'Sale Manage' => '',
    'Sale Manage Instruction' => '',
    'Save' => 'Lưu lại',
    'Search' => 'Tìm kiếm',
    'Search contact' => '',
    'Search employee' => 'Tìm kiếm nhân viên',
    'Status' => 'Trạng thái',
    'The above error occurred while the Web server was processing your request.' => 'Lỗi trên xảy ra khi máy chủ web xử lý yêu cầu của bạn',
    'This email address has already been taken' => 'Email này đã được sử dụng',
    'This username has already been taken' => 'Username này đã được sử dụng',
    'Traffic Overview' => 'Tổng quan lưu lượng truy cập',
    'Unblock' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => 'Sửa lúc',
    'Updated By' => 'Sửa bởi',
    'Updating' => '',
    'Username' => 'Tên đăng nhập',
    'Web Manage Instruction' => '',
    'Website Manage' => '',
    'Your account have been blocked.' => '',
    'Your account have been deleted.' => '',
    'Your account have no roles in system.' => '',
];
