<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add New' => '',
    'Are you sure to delete this item?' => '',
    'Auth Key' => '',
    'Avatar' => 'Ảnh đại diện',
    'Back' => 'Quay lại',
    'Birthday' => 'Ngày sinh',
    'Cancel' => 'Hủy',
    'Comfirm Passwords don\'t match' => '',
    'Confirm Password' => '',
    'Contact Information' => '',
    'Countries' => 'Quốc gia',
    'Country ID' => '',
    'Create' => 'Tạo',
    'Created At' => 'Tạo lúc',
    'Data provided by' => 'Dữ liệu cung cấp bởi',
    'Delete' => 'Xóa',
    'Description' => 'Mô tả',
    'Edit' => 'Sửa',
    'Edit Employee' => 'Sửa nhân viên',
    'Email' => '',
    'Employees' => 'Nhân viên',
    'Famale' => 'Nữ',
    'Film Actors' => 'Diễn viên phim',
    'Film Categories' => 'Thể loại phim',
    'First' => 'Đầu',
    'Fullname' => 'Họ và tên',
    'Gender' => 'Giới tính',
    'Home' => 'Trang chủ',
    'ID' => '',
    'Last' => 'Cuối',
    'Log out' => 'Đăng xuất',
    'Male' => '',
    'Meanwhile, you may return to Home' => 'Trong khi đó, bạn có thể trở về Trang chủ',
    'Monthly' => 'Tháng',
    'Name' => 'Tên',
    'New' => 'Mới',
    'Other Name' => 'Tên khác',
    'Password' => 'Mật khẩu',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Phone' => 'Điện thoại',
    'Please contact us if you think this is a server error. Thank you.' => 'Hãy liên hệ với chúng tôi nếu bạn nghĩ rằng đây là một lỗi máy chủ. Cảm ơn.',
    'Profile' => 'Tiểu sử',
    'Roles' => 'Các vai trò',
    'Save' => 'Lưu lại',
    'Search' => 'Tìm kiếm',
    'Search employee' => 'Tìm kiếm nhân viên',
    'Status' => 'Trạng thái',
    'The above error occurred while the Web server was processing your request.' => 'Lỗi trên xảy ra khi máy chủ web xử lý yêu cầu của bạn',
    'This email address has already been taken' => 'Email này đã được sử dụng',
    'This username has already been taken' => 'Username này đã được sử dụng',
    'Traffic Overview' => 'Tổng quan lưu lượng truy cập',
    'Updated At' => 'Sửa lúc',
    'Username' => 'Tên đăng nhập',
    'View' => 'Xem',
];
